# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: agent.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'agent.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x61gent.proto\"\x1d\n\x0c\x41gentRequest\x12\r\n\x05query\x18\x01 \x01(\t\"!\n\rAgentResponse\x12\x10\n\x08response\x18\x01 \x01(\t2A\n\x0c\x41gentService\x12\x31\n\x0e\x41skAgentStream\x12\r.AgentRequest\x1a\x0e.AgentResponse0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'agent_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_AGENTREQUEST']._serialized_start=15
  _globals['_AGENTREQUEST']._serialized_end=44
  _globals['_AGENTRESPONSE']._serialized_start=46
  _globals['_AGENTRESPONSE']._serialized_end=79
  _globals['_AGENTSERVICE']._serialized_start=81
  _globals['_AGENTSERVICE']._serialized_end=146
# @@protoc_insertion_point(module_scope)
